chore(repo): cleanup scripts and simplify package installation + testing

diff --git a/scripts/lint-staged-files b/scripts/lint-staged-files
--- a/scripts/lint-staged-files
+++ b/scripts/lint-staged-files
@@ -1,15 +1,21 @@
-#!/usr/bin/env bash
+#!/bin/bash -e
 
 # Lints staged js-files
 
 # find staged files which end in ".js"
 # eslint will exclude the ones ignored by .eslintignore even if we pass them
 # explicitly
+set +e
 FILES="$(git diff --cached --name-only --diff-filter=ACM | grep '\.js$')"
+set -e
 
-if [ $? -eq 0 ]; then
+# If grep didn't find any match (fails), simply exit
+if [ $? -eq 1 ]; then
+  exit 0
+fi
+
+# If there are matching files, lint them
+if [ -n "$FILES" ]; then
   # lint these files
   ./scripts/lint $FILES
-else
-  exit 0
 fi
